version: "1.0.0"
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    image: employeer_hub_front
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    container_name: employeer_hub_front
    ports:
      - ${PORT}:${PORT}
    tty: true
    entrypoint: ["npm", "run", "dev"]
