version: "1.0.0"
services:
  ehdb:
    image: mongo:7.0.6
    container_name: ${MONGO_DB_NAME}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  local:
    build:
      context: .
      dockerfile: Dockerfile
    image: employeer_hub_back
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    container_name: employeer_hub_back
    ports:
      - ${PORT}:${PORT}
    entrypoint: ["npm", "run", "dev"]
    depends_on:
      - ehdb
